const employees = [
  {
    id: 1,
    firstName: "Prakash",
    email: "a@b.d",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Description of task 1",
        date: "2025-01-12",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Description of task 2",
        date: "2025-01-13",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Description of task 3",
        date: "2025-01-14",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Santosh",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Description of task 1",
        date: "2025-01-12",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Description of task 2",
        date: "2025-01-13",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 2,
      completed: 0,
      failed: 0,
    },
  },
  {
    id: 3,
    firstName: "Binita",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Description of task 1",
        date: "2025-01-12",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Description of task 2",
        date: "2025-01-13",
        category: "Design",
        active: true,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Description of task 3",
        date: "2025-01-14",
        category: "Deployment",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Task 4",
        description: "Description of task 4",
        date: "2025-01-15",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    firstName: "Manisha",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Description of task 1",
        date: "2025-01-12",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Description of task 2",
        date: "2025-01-13",
        category: "Design",
        active: true,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Description of task 3",
        date: "2025-01-14",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Task 4",
        description: "Description of task 4",
        date: "2025-01-15",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Description of task 5",
        date: "2025-01-16",
        category: "Deployment",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 3,
      newTask: 2,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 5,
    firstName: "Anita",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Description of task 1",
        date: "2025-01-12",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Description of task 2",
        date: "2025-01-13",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Task 3",
        description: "Description of task 3",
        date: "2025-01-14",
        category: "Deployment",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 2,
      completed: 0,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employeesData = JSON.parse(localStorage.getItem("employees"));
  const adminData = JSON.parse(localStorage.getItem("admin"));

  return { employeesData, adminData };
};
